
---

language: node_js

node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=7be4d1233325d348c0d14548f814c38e10b82e126519861879af6d5338324f55

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 